---
title: "Recording Analysis"
subtitle: "GEOG 394 Capturing Personal Exposures Across Space and Time"
author: "Alayna Johnson"
date: "February 17, 2025"
format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
    code-tools: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, warning = FALSE)
```

# Loading Dependencies

```{r loading-packages}
#| message: false

library(tidyverse)
library(ggplot2)
library(plotly)
library(sf)
library(leaflet)
library(viridis)

library(RColorBrewer)
```

Data for February 19th, 2025

```{r reading-data1}
#| message: false
grand_east_west1 <- read_csv("data/raw-data/feb19-raw/23_53_Snelling_Ave_S-2025-19-2_3-33-02 PM.csv")
grand_west_east1 <- read_csv("data/raw-data/feb19-raw/30_Fairview_Ave_S-2025-19-2_3-40-03 PM.csv")

snelling_north_south_right_part1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_3-41-54 PM.csv")
snelling_north_south_right_small1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_4-02-02 PM.csv")
snelling_north_south_left1 <- read_csv("data/raw-data/feb19-raw/Snelling_Ave_N-2025-19-2_3-47-43 PM.csv")
snelling_south_north_right1 <- read_csv("data/raw-data/feb19-raw/224_244_Snelling_Ave_S-2025-19-2_3-54-16 PM.csv")
snelling_south_north_left_part1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_3-31-46 PM.csv")

lincoln1 <- read_csv("data/raw-data/feb19-raw/100_110_Fairview_Ave_S-2025-19-2_4-17-30 PM.csv")

fairview_south_north1 <- read_csv("data/raw-data/feb19-raw/232_Fairview_Ave_S-2025-19-2_3-44-20 PM.csv")
fairview_north_south1 <- read_csv("data/raw-data/feb19-raw/Fairview_Ave_N-2025-19-2_3-27-57 PM.csv")

saintclair_east_west1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_3-43-07 PM.csv")
saintclair_west_east1 <- read_csv("data/raw-data/feb19-raw/265_299_Fairview_Ave_S-2025-19-2_3-29-41 PM.csv")

summit_east_west1 <- read_csv("data/raw-data/feb19-raw/Summit_Ave-2025-19-2_3-26-14 PM.csv")
summit_west_east1 <- read_csv("data/raw-data/feb19-raw/1794_1818_Summit_Ave-2025-19-2_3-45-53 PM.csv")
summit_east_west_side1 <- read_csv("data/raw-data/feb19-raw/1583_Summit_Ave-2025-19-2_3-56-43 PM.csv")
summit_west_east_side1 <- read_csv("data/raw-data/feb19-raw/1750_Summit_Ave-2025-19-2_4-00-23 PM.csv")

# all have snow built up
cambridge_north_south1 <- read_csv("data/raw-data/feb19-raw/Summit_Ave-2025-19-2_4-12-59 PM.csv")
cambridge_south_north1 <- read_csv("data/raw-data/feb19-raw/Cambridge_Triangle-2025-19-2_4-06-21 PM.csv")
vernon_north_south1 <- read_csv("data/raw-data/feb19-raw/Cambridge_Triangle-2025-19-2_4-14-51 PM.csv")
vernon_south_north1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_4-05-24 PM.csv")


mac_street_north_south1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_4-03-06 PM.csv")
mac_street_south_north1 <- read_csv("data/raw-data/feb19-raw/Macalester_College-2025-19-2_4-24-20 PM.csv")

```

Data for February 27th, 2025

```{r reading-data2}
#| message: FALSE
#errant points in most data at time 0 or 1

summit_east_west2 <- read_csv("data/raw-data/feb27-raw/1559_Portland_Ave-2025-27-2_7-05-48 PM.csv")
summit_west_east_side2 <- read_csv("data/raw-data/feb27-raw/2_46_Fairview_Ave_S-2025-27-2_7-21-44 PM.csv")
summit_east_west_side2 <- read_csv("data/raw-data/feb27-raw/43_69_Snelling_Ave_N-2025-27-2_7-17-59 PM.csv")
summit_west_east2 <- read_csv("data/raw-data/feb27-raw/1818_Summit_Ave-2025-27-2_7-39-20 PM.csv")

grand_west_east2 <- read_csv("data/raw-data/feb27-raw/58_66_Fairview_Ave_S-2025-27-2_7-07-08 PM.csv")
grand_east_west2 <- read_csv("data/raw-data/feb27-raw/Macalester_College-2025-27-2_7-23-31 PM.csv")

saintclair_west_east2 <- read_csv("data/raw-data/feb27-raw/232_Fairview_Ave_S-2025-27-2_6-58-09 PM.csv")
saintclair_east_west2 <- read_csv("data/raw-data/feb27-raw/Macalester_College-2025-27-2_7-36-58 PM.csv")

snelling_south_north_right2 <- read_csv("data/raw-data/feb27-raw/1518_Saint_Clair_Ave-2025-27-2_7-14-57 PM.csv")
snelling_south_north_left2 <- read_csv("data/raw-data/feb27-raw/1562_1596_Saint_Clair_Ave-2025-27-2_7-00-20 PM.csv")
snelling_north_south_right2 <- read_csv("data/raw-data/feb27-raw/1576_Portland_Ave-2025-27-2_7-35-22 PM.csv")
snelling_north_south_left2 <- read_csv("data/raw-data/feb27-raw/Saratoga_St_N-2025-27-2_7-11-33 PM.csv")

fairview_south_north2 <- read_csv("data/raw-data/feb27-raw/1813_1819_Saint_Clair_Ave-2025-27-2_7-38-09 PM.csv")
fairview_north_south2 <- read_csv("data/raw-data/feb27-raw/Cambridge_St-2025-27-2_6-56-48 PM.csv")


lincoln2 <- read_csv("data/raw-data/feb27-raw/1820_Grand_Ave-2025-27-2_7-24-59 PM.csv")

vernon_cambridge2 <- read_csv("data/raw-data/feb27-raw/Macalester_College-2025-27-2_6-53-24 PM.csv")

mac_street2 <- read_csv("data/raw-data/feb27-raw/Macalester_College-2025-27-2_7-29-01 PM.csv")

```

Data for March 6th, 2025

```{r reading-data3}
#| message: false
saintclair_west_east3 <- read_csv("data/raw-data/mar06-raw/265_299_Fairview_Ave_S-2025-6-3_6-26-15 PM.csv")
saintclair_east_west3 <- read_csv("data/raw-data/mar06-raw/Macalester_College-2025-6-3_6-49-03 PM.csv")

#check
summit_east_west_side3 <- read_csv("data/raw-data/mar06-raw/1543_Portland_Ave-2025-6-3_6-42-10 PM.csv")
#good
summit_west_east3 <- read_csv("data/raw-data/mar06-raw/1826_Summit_Ave-2025-6-3_6-31-57 PM.csv")
summit_west_east_side3 <- read_csv("data/raw-data/mar06-raw/1826_Summit_Ave-2025-6-3_6-45-16 PM.csv")
summit_east_west3 <- read_csv("data/raw-data/mar06-raw/Summit_Ave-2025-6-3_6-30-06 PM.csv")

fairview_south_north3 <- read_csv("data/raw-data/mar06-raw/Cambridge_St-2025-6-3_6-24-47 PM.csv")
fairview_north_south3 <-read_csv("data/raw-data/mar06-raw/1813_1819_Saint_Clair_Ave-2025-6-3_6-50-24 PM.csv")


snelling_north_south_right3 <- read_csv("data/raw-data/mar06-raw/1580_1606_Summit_Ave-2025-6-3_6-47-29 PM.csv")
snelling_north_south_left3 <- read_csv("data/raw-data/mar06-raw/Summit_Ave-2025-6-3_6-33-20 PM.csv")
snelling_south_north_left3 <- read_csv("data/raw-data/mar06-raw/Saint_Clair_Ave-2025-6-3_6-27-38 PM.csv")
snelling_south_north_right3 <- read_csv("data/raw-data/mar06-raw/1560_Saint_Clair_Ave-2025-6-3_6-38-19 PM.csv")

grand_west_east3 <- read_csv("data/raw-data/mar06-raw/1818_Summit_Ave-2025-6-3_6-56-16 PM.csv")
grand_east_west3 <- read_csv("data/raw-data/mar06-raw/Macalester_College-2025-6-3_7-00-35 PM.csv")

vernon_cambridge3 <- read_csv("data/raw-data/mar06-raw/Macalester_College-2025-6-3_6-20-45 PM.csv")

mac_street3 <- read_csv("data/raw-data/mar06-raw/30_Fairview_Ave_S-2025-6-3_7-04-00 PM.csv")

lincoln3 <- read_csv("data/raw-data/mar06-raw/99_Fairview_Ave_S-2025-6-3_7-08-12 PM.csv")

```

Data for March 13th, 2025

```{r reading-data4}
#| message: false
# fix!
summit_west_east_side4 <- read_csv("data/raw-data/mar13-raw/1_25_Fairview_Ave_S-2025-13-3_9-02-03 PM.csv")

summit_west_east4 <- read_csv("data/raw-data/mar13-raw/2_46_Fairview_Ave_S-2025-13-3_9-08-10 PM.csv")
summit_east_west_side4 <- read_csv("data/raw-data/mar13-raw/43_69_Snelling_Ave_N-2025-13-3_9-17-41 PM.csv")
summit_east_west4 <- read_csv("data/raw-data/mar13-raw/Summit_Ave-2025-13-3_9-24-21 PM.csv")

fairview_south_north4 <- read_csv("data/raw-data/mar13-raw/232_Fairview_Ave_S-2025-13-3_9-06-57 PM.csv")
fairview_north_south4 <- read_csv("data/raw-data/mar13-raw/1747_Summit_Ave-2025-13-3_9-19-31 PM.csv")

saintclair_west_east4 <- read_csv("data/raw-data/mar13-raw/265_299_Fairview_Ave_S-2025-13-3_9-21-03 PM.csv")
saintclair_east_west4 <- read_csv("data/raw-data/mar13-raw/Macalester_College-2025-13-3_9-05-43 PM.csv")

grand_west_east4 <- read_csv("data/raw-data/mar13-raw/Fairview_Ave_N-2025-13-3_9-26-13 PM.csv")
grand_east_west4 <- read_csv("data/raw-data/mar13-raw/Macalester_College-2025-13-3_9-36-14 PM.csv")

snelling_south_north_right4 <- read_csv("data/raw-data/mar13-raw/1556_Saint_Clair_Ave-2025-13-3_9-15-03 PM.csv")
snelling_south_north_left4 <- read_csv("data/raw-data/mar13-raw/1562_1596_Saint_Clair_Ave-2025-13-3_9-22-41 PM.csv")
snelling_north_south_right4 <- read_csv("data/raw-data/mar13-raw/1580_1606_Summit_Ave-2025-13-3_9-04-00 PM.csv")
snelling_north_south_left4 <- read_csv("data/raw-data/mar13-raw/Summit_Ave-2025-13-3_9-09-25 PM.csv")

mac_street4 <- read_csv("data/raw-data/mar13-raw/Summit_Ave-2025-13-3_9-28-49 PM.csv")

lincoln4 <- read_csv("data/raw-data/mar13-raw/Macalester_College-2025-13-3_8-59-34 PM.csv")

vernon_cambridge4 <- read_csv("data/raw-data/mar13-raw/Macalester_College-2025-13-3_9-33-02 PM.csv")
```

Data for March 20th, 2025

```{r reading-data5}
#| message: false
summit_west_east5 <- read_csv("data/raw-data/mar20-raw/2_46_Fairview_Ave_S-2025-20-3_7-20-11 PM.csv")
summit_west_east_side5 <- read_csv("data/raw-data/mar20-raw/1740_Summit_Ave-2025-20-3_7-34-17 PM.csv")
summit_east_west5 <- read_csv("data/raw-data/mar20-raw/Summit_Ave-2025-20-3_7-04-30 PM.csv")
summit_east_west_side5 <- read_csv("data/raw-data/mar20-raw/1583_Summit_Ave-2025-20-3_7-31-05 PM.csv")

fairview_south_north5 <- read_csv("data/raw-data/mar20-raw/232_Fairview_Ave_S-2025-20-3_7-18-58 PM.csv")
fairview_north_south5 <- read_csv("data/raw-data/mar20-raw/Fairview_Ave_N-2025-20-3_7-05-40 PM.csv")

saintclair_west_east5 <- read_csv("data/raw-data/mar20-raw/265_299_Fairview_Ave_S-2025-20-3_7-07-07 PM.csv")
saintclair_east_west5 <- read_csv("data/raw-data/mar20-raw/Macalester_College-2025-20-3_7-17-18 PM.csv")

# missing snelling south to north right lane 
snelling_south_north_left5 <- read_csv("data/raw-data/mar20-raw/Saint_Clair_Ave-2025-20-3_7-08-16 PM.csv")
snelling_north_south_right5 <- read_csv("data/raw-data/mar20-raw/Summit_Ave-2025-20-3_7-16-07 PM.csv")
snelling_north_south_left5 <- read_csv("data/raw-data/mar20-raw/Summit_Ave-2025-20-3_7-21-40 PM.csv")

grand_west_east5 <- read_csv("data/raw-data/mar20-raw/1818_Grand_Ave-2025-20-3_7-41-01 PM.csv")
grand_east_west5 <- read_csv("data/raw-data/mar20-raw/Macalester_College-2025-20-3_7-35-58 PM.csv")

mac_street5 <- read_csv("data/raw-data/mar20-raw/Summit_Ave-2025-20-3_7-10-07 PM.csv")


lincoln5 <- read_csv("data/raw-data/mar20-raw/1815_Lincoln_Ave-2025-20-3_7-37-40 PM.csv")

vernon_cambridge5 <- read_csv("data/raw-data/mar20-raw/Macalester_College-2025-20-3_7-12-57 PM.csv")

```

Data for March 27th, 2025

```{r reading-data6}
#| message: false
fairview_south_north6 <- read_csv("data/raw-data/mar27-raw/232_Fairview_Ave_S-2025-27-3_9-41-33 PM.csv") 
fairview_north_south6 <- read_csv("data/raw-data/mar27-raw/1825_Summit_Ave-2025-27-3_9-27-58 PM.csv")

snelling_south_north_left6 <- read_csv("data/raw-data/mar27-raw/224_244_Snelling_Ave_S-2025-27-3_9-31-17 PM.csv")
snelling_south_north_right6 <- read_csv("data/raw-data/mar27-raw/240_Snelling_Ave_S-2025-27-3_9-50-52 PM.csv")
snelling_north_south_left6 <- read_csv("data/raw-data/mar27-raw/Macalester_College-2025-27-3_9-46-17 PM.csv")
snelling_north_south_right6 <- read_csv("data/raw-data/mar27-raw/1580_1606_Summit_Ave-2025-27-3_9-39-20 PM.csv")


summit_east_west6 <- read_csv("data/raw-data/mar27-raw/Snelling_Ave_N-2025-27-3_9-18-10 PM.csv")
summit_east_west_side6 <- read_csv("data/raw-data/mar27-raw/Snelling_Ave_N-2025-27-3_9-53-40 PM.csv")
summit_west_east6 <- read_csv("data/raw-data/mar27-raw/2_46_Fairview_Ave_S-2025-27-3_9-59-32 PM.csv")
summit_west_east_side6 <- read_csv("data/raw-data/mar27-raw/1732_Summit_Ave-2025-27-3_9-44-39 PM.csv")

grand_west_east6 <- read_csv("data/raw-data/mar27-raw/1795_1799_Grand_Ave-2025-27-3_10-02-49 PM.csv")
grand_east_west6 <- read_csv("data/raw-data/mar27-raw/Macalester_College-2025-27-3_10-01-03 PM.csv")

saintclair_west_east6 <- read_csv("data/raw-data/mar27-raw/1818_Saint_Clair_Ave-2025-27-3_9-29-13 PM.csv")
saintclair_east_west6 <- read_csv("data/raw-data/mar27-raw/Macalester_College-2025-27-3_9-40-22 PM.csv")

vernon_cambridge6 <- read_csv("data/raw-data/mar27-raw/Macalester_College-2025-27-3_9-36-13 PM.csv")

lincoln6 <- read_csv("data/raw-data/mar27-raw/1814_Lincoln_Ave-2025-27-3_9-56-23 PM.csv")

mac_street6 <- read_csv("data/raw-data/mar27-raw/Summit_Ave-2025-27-3_9-33-22 PM.csv")

```

Data for April 3rd, 2025

```{r reading-data7}
#| message: false
fairview_south_north7 <- read_csv("data/raw-data/apr03-raw/232_Fairview_Ave_S-2025-3-4_10-28-26 PM.csv")
fairview_north_south7 <- read_csv("data/raw-data/apr03-raw/1815_Summit_Ave-2025-3-4_10-11-31 PM.csv")

snelling_south_north_right7 <- read_csv("data/raw-data/apr03-raw/240_Snelling_Ave_S-2025-3-4_10-36-39 PM.csv")
snelling_south_north_left7 <- read_csv("data/raw-data/apr03-raw/243_Snelling_Ave_S-2025-3-4_10-15-05 PM.csv")
snelling_north_south_left7 <- read_csv("data/raw-data/apr03-raw/Snelling_Ave_N-2025-3-4_10-31-44 PM.csv")
snelling_north_south_right7 <- read_csv("data/raw-data/apr03-raw/Macalester_College-2025-3-4_10-25-58 PM.csv")

summit_east_west7 <- read_csv("data/raw-data/apr03-raw/Summit_Ave-2025-3-4_10-10-08 PM.csv")
summit_east_west_side7 <- read_csv("data/raw-data/apr03-raw/1583_Summit_Ave-2025-3-4_10-38-53 PM.csv")
summit_west_east7 <- read_csv("data/raw-data/apr03-raw/1818_Summit_Ave-2025-3-4_10-30-07 PM.csv")
summit_west_east_side7 <- read_csv("data/raw-data/apr03-raw/1740_Summit_Ave-2025-3-4_10-24-22 PM.csv")


grand_west_east7 <- read_csv("data/raw-data/apr03-raw/1827_Grand_Ave-2025-3-4_10-49-16 PM.csv")
grand_east_west7 <- read_csv("data/raw-data/apr03-raw/Macalester_College-2025-3-4_10-47-29 PM.csv")

saintclair_east_west7 <- read_csv("data/raw-data/apr03-raw/Macalester_College-2025-3-4_10-27-08 PM.csv")
saintclair_west_east7 <- read_csv("data/raw-data/apr03-raw/1813_1819_Saint_Clair_Ave-2025-3-4_10-13-04 PM.csv")

vernon_cambridge7 <- read_csv("data/raw-data/apr03-raw/Macalester_College-2025-3-4_10-19-46 PM.csv")

mac_street7 <- read_csv("data/raw-data/apr03-raw/1607_1629_Summit_Ave-2025-3-4_10-16-47 PM.csv")

lincoln7 <- read_csv("data/raw-data/apr03-raw/1814_Lincoln_Ave-2025-3-4_10-41-28 PM.csv")


```



# Recordings

## Combining Data

```{r function-combining-data}
# Creating a function that takes in a list of data sets, joins them, and takes out any unnecessary variables in data

# combine_recordings <- function(dataset_list, name_prefix) {
#   combined_data <- bind_rows(dataset_list) %>%
#      mutate(accelerometer_y_new = -1 * accelerometer_y,
#          accelerometer_x_new = -1 * accelerometer_x) %>%
#     mutate(L2_norm = sqrt(accelerometer_y_new^2 + accelerometer_x_new^2 + accelerometer_z^2)) %>%
#   filter(!is.na(location_longitude)& !is.na(location_latitude)) %>%
#   dplyr::select(-location_altitude, -location_speedAccuracy, -location_bearingAccuracy, - location_altitudeAboveMeanSeaLevel, -location_bearing, -location_horizontalAccuracy, -location_verticalAccuracy, -location_speed, -accelerometerUncalibrated_z, -accelerometerUncalibrated_x, -accelerometerUncalibrated_y, -accelerometerUncalibrated_local_time, -accelerometer_x, -accelerometer_y, -accelerometer_local_time) %>%
#     filter(seconds_elapsed != 0)
#   
# 
#   # Changing the data name to name_prefix_combined
#   data <- assign(paste0(name_prefix, "_combined"), combined_data, envir = .GlobalEnv)
#   
#   data <- tibble::rowid_to_column(data, "ID")
# 
# }

```


Improving previous function

```{r}
# Function to label streets and combine datasets
label_and_combine <- function(dataset_list, name_prefix) {
  
   if (is.null(names(dataset_list)) || any(names(dataset_list) == "")) {
    list_expr <- as.list(substitute(dataset_list))[-1]
    names(dataset_list) <- sapply(list_expr, deparse)
  }

  # Function inside function to use similar naming conventions from naming the data before in order to get the street name label (street_name variable value)
  get_street_name <- function(name) {
    case_when(
      str_detect(name, "grand_east_west") ~ "Grand Avenue West",
      str_detect(name, "grand_west_east") ~ "Grand Avenue East",
      str_detect(name, "snelling_north_south_right") ~ "Snelling Avenue South R",
      str_detect(name, "snelling_north_south_left") ~ "Snelling Avenue South L",
      str_detect(name, "snelling_south_north_right") ~ "Snelling Avenue North R",
      str_detect(name, "snelling_south_north_left") ~ "Snelling Avenue North L",
      str_detect(name, "fairview_north_south") ~ "Fairview Avenue South",
      str_detect(name, "fairview_south_north") ~ "Fairview Avenue North",
      str_detect(name, "saintclair_north_south") ~ "St. Clair Avenue South",
      str_detect(name, "saintclair_south_north") ~ "St. Clair Avenue North",
      str_detect(name, "summit_east_west_side") ~ "Summit Avenue West S",
      str_detect(name, "summit_west_east_side") ~ "Summit Avenue East S",
      str_detect(name, "summit_east_west") ~ "Summit Avenue West",
      str_detect(name, "summit_west_east") ~ "Summit Avenue East",
      str_detect(name, "mac_street") ~ "Macalester Street",
      str_detect(name, "vernon|cambridge") ~ "Vernon and Cambridge",
      str_detect(name, "lincoln") ~ "Lincoln Avenue",
      TRUE ~ "Unknown"
    )
  }

  # Function inside function to street name column to each dataset
  updated_list <- Map(function(data, name) {
    data$street_name <- get_street_name(name)
    return(data)
  }, dataset_list, names(dataset_list))

  # Combine data
  combined_data <- bind_rows(updated_list) %>%
    mutate(
      accelerometer_y_new = -1 * accelerometer_y,
      accelerometer_x_new = -1 * accelerometer_x,
      L2_norm = sqrt(accelerometer_y_new^2 + accelerometer_x_new^2 + accelerometer_z^2)
    ) %>%
    filter(!is.na(location_longitude) & !is.na(location_latitude)) %>%
    select(
      -location_altitude, -location_speedAccuracy, -location_bearingAccuracy,
      -location_altitudeAboveMeanSeaLevel, -location_bearing, -location_horizontalAccuracy,
      -location_verticalAccuracy, -location_speed,
      -accelerometerUncalibrated_z, -accelerometerUncalibrated_x,
      -accelerometerUncalibrated_y, -accelerometerUncalibrated_local_time,
      -accelerometer_x, -accelerometer_y, -accelerometer_local_time
    ) %>%
    filter(seconds_elapsed != 0) %>%
    tibble::rowid_to_column("ID")

  assign(paste0(name_prefix, "_combined"), combined_data, envir = .GlobalEnv)

  return(combined_data)
}

```


## Visualizations

```{r}
# function to take teh lists from below and make their names the same as the input in order to use them for the function before
name_list <- function(...) {
  args <- substitute(list(...))[-1]
  setNames(list(...), sapply(args, deparse))
}
```


```{r lists-of-data}
# Creating lists of data sets to combine
feb19_recs <- name_list(
  grand_east_west1, grand_west_east1,
  snelling_north_south_right_part1, snelling_north_south_right_small1,
  snelling_north_south_left1, snelling_south_north_right1,
  snelling_south_north_left_part1, lincoln1,
  fairview_south_north1, fairview_north_south1,
  saintclair_east_west1, saintclair_west_east1,
  summit_east_west1, summit_west_east1,
  summit_east_west_side1, summit_west_east_side1,
  cambridge_north_south1, cambridge_south_north1,
  vernon_north_south1, vernon_south_north1,
  mac_street_north_south1, mac_street_south_north1
)

feb27_recs <- name_list(
  grand_east_west2, grand_west_east2,
  snelling_north_south_right2,
  snelling_north_south_left2, snelling_south_north_right2,
  snelling_south_north_left2,
  fairview_south_north2, fairview_north_south2,
  saintclair_east_west2, saintclair_west_east2,
  summit_east_west2, summit_west_east2,
  summit_east_west_side2, summit_west_east_side2,
  vernon_cambridge2, lincoln2, mac_street2
  )

mar06_recs <- name_list(
  grand_east_west3, grand_west_east3,
  snelling_north_south_right3,
  snelling_north_south_left3, snelling_south_north_right3,
  snelling_south_north_left3,
  fairview_south_north3, fairview_north_south3,
  saintclair_east_west3, saintclair_west_east3,
  summit_east_west3, summit_west_east3,
  summit_east_west_side3, summit_west_east_side3,
  vernon_cambridge3, lincoln3, mac_street3
  )

mar13_recs <- name_list(
  grand_east_west4, grand_west_east4,
  snelling_north_south_right4,
  snelling_north_south_left4, snelling_south_north_right4,
  snelling_south_north_left4,
  fairview_south_north4, fairview_north_south4,
  saintclair_east_west4, saintclair_west_east4,
  summit_east_west4, summit_west_east4,
  summit_east_west_side4, summit_west_east_side4,
  vernon_cambridge4, lincoln4, mac_street4
  )

mar20_recs <- name_list(grand_east_west5, grand_west_east5,
  snelling_north_south_right5,
  snelling_north_south_left5,
  snelling_south_north_left5,
  fairview_south_north5, fairview_north_south5,
  saintclair_east_west5, saintclair_west_east5,
  summit_east_west5, summit_west_east5,
  summit_east_west_side5, summit_west_east_side5,
  vernon_cambridge5, lincoln5, mac_street5
  
)

mar27_recs <- name_list(grand_east_west6, grand_west_east6,
  snelling_north_south_right6,
  snelling_north_south_left6, snelling_south_north_right6,
  snelling_south_north_left6,
  fairview_south_north6, fairview_north_south6,
  saintclair_east_west6, saintclair_west_east6,
  summit_east_west6, summit_west_east6,
  summit_east_west_side6, summit_west_east_side6,
  vernon_cambridge6, lincoln6, mac_street6
  
)

apr03_recs <- name_list(grand_east_west7, grand_west_east7,
  snelling_north_south_right7,
  snelling_north_south_left7, snelling_south_north_right7,
  snelling_south_north_left7,
  fairview_south_north7, fairview_north_south7,
  saintclair_east_west7, saintclair_west_east7,
  summit_east_west7, summit_west_east7,
  summit_east_west_side7, summit_west_east_side7,
  vernon_cambridge7, lincoln7, mac_street7
  
)
```


```{r calling-function}
# Calling the function for recordings using lists from above
label_and_combine(feb19_recs, "feb19")
label_and_combine(feb27_recs, "feb27")
label_and_combine(mar06_recs, "mar06")
label_and_combine(mar13_recs, "mar13")
label_and_combine(mar20_recs, "mar20")
label_and_combine(mar27_recs, "mar27")
label_and_combine(apr03_recs, "apr03")

```

```{r eval = FALSE}
# saving csv created from function in cleaned data. Only needs to be done once
write_csv(feb19_combined, "data/cleaned-data/combined-clean/feb19-clean.csv")
write_csv(feb27_combined, "data/cleaned-data/combined-clean/feb27-clean.csv")
write_csv(mar06_combined, "data/cleaned-data/combined-clean/mar06-clean.csv")
write_csv(mar13_combined, "data/cleaned-data/combined-clean/mar13-clean.csv")
write_csv(mar20_combined, "data/cleaned-data/combined-clean/mar20-clean.csv")
write_csv(mar27_combined, "data/cleaned-data/combined-clean/mar27-clean.csv")
write_csv(apr03_combined, "data/cleaned-data/combined-clean/apr03-clean.csv")

```


```{r}
save_cleaned_csvs <- function(dataset_list, folder_path = "data/cleaned-data/separate-clean") {
  # making sure the folder path exists
  if (!dir.exists(folder_path)) dir.create(folder_path, recursive = TRUE)
  
  # saving each data as csv
  for (name in names(dataset_list)) {
    file_path <- file.path(folder_path, paste0(name, "-clean.csv"))
    readr::write_csv(dataset_list[[name]], file_path)
  }
}
```


```{r}
save_cleaned_csvs(feb19_recs)
save_cleaned_csvs(feb27_recs)
save_cleaned_csvs(mar06_recs)
save_cleaned_csvs(mar13_recs)
save_cleaned_csvs(mar20_recs)
save_cleaned_csvs(mar27_recs)
save_cleaned_csvs(apr03_recs)
```


```{r eval = FALSE}
# For viewing each data to see what street and direction

mac4 <- mac4 %>%
  mutate(accelerometer_y_new = -1 * accelerometer_y,
         accelerometer_x_new = -1 * accelerometer_x) %>%
  filter(!is.na(location_longitude)& !is.na(location_latitude)) %>%
  select(-location_altitude, -location_speedAccuracy, -location_bearingAccuracy, -location_altitudeAboveMeanSeaLevel, -location_bearing, -location_horizontalAccuracy, -location_verticalAccuracy, -location_speed, -accelerometerUncalibrated_z, -accelerometerUncalibrated_x, -accelerometerUncalibrated_y, -accelerometerUncalibrated_local_time, -accelerometer_x, -accelerometer_y, -accelerometer_local_time)

mac4 <- st_as_sf(mac4, coords = c("location_longitude", "location_latitude"), crs = 4326)


pal <- colorNumeric(palette = rev(viridis::turbo(100)), domain = mac4$accelerometer_y_new)

# Create Leaflet map
leaflet(mac4) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(
    radius = 1,
    color = ~pal(accelerometer_y_new),
    weight = 5,
    opacity = 0.9,
    popup = ~paste0("Acceleration Y: ", accelerometer_y_new, "Time elapsed: ", seconds_elapsed)
  ) %>%
  addLegend(
    pal = pal, 
    values = mac4$accelerometer_y_new, 
    title = "Accelerometer Y",
    opacity = 1
  )
```

```{r}
#| cache: true

# Created road lines in Arc, visualizing them here

roads <- read_sf("data/raw-data/macalester_road_lines/macalester_road_lines.shp")

roads <- st_transform(roads, crs = 4326)


leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolylines(data = roads)

```

```{r}
library(sfdep)

feb27_combined <- tibble::rowid_to_column(feb27_combined, "ID") # creating arbitrary id column

time_period <- 1

feb27_combined <- cbind(feb27_combined, time_period)

new_data <- as_spacetime(feb19_combined, "ID", "time_period")
```

```{r}

process_datasets <- function(dataset_list) {
  id_counter <- 1
  time_period <- 1
  processed_list <- list()
  
  for (i in seq_along(dataset_list)) {
    df <- dataset_list[[i]]
        df <- df %>%
      mutate(ID = id_counter:(id_counter + nrow(df) - 1)) # creating unique ids for all observations
        df <- cbind(df, time_period) # each df has its own time period
    
    df_spacetime <- as_spacetime(df, "ID", "time_period") # spacetime object
    
    processed_list[[i]] <- df_spacetime
    
    id_counter <- id_counter + nrow(df)
    time_period <- time_period + 1
  }
  
  return(processed_list)
}

dataset_list <- list(feb27_combined, mar06_combined, mar13_combined, mar20_combined)
processed_data <- process_datasets(dataset_list)

```




```{r}
library(sqldf)

sqldf
```

